### ISSUE TITLE
Refactoring the game

### ISSUE THREAD

**Issue by Moresty** [Mysteryquy/Roguelike#11]
Hello pls make multiple files thx

**Comment by Mysteryquy** [comment]
Explain plox

**Comment by Mysteryquy** [comment]
Why should we do that? Then we have to alway write a x.WHATEVERWENEED :⭕️

**Comment by Moresty** [comment]
Bruh the file has over 600 lines that's way too much. Also there are multiple things that are not related to eachother in the same file. E.g. the creation of the map and the actor class

**Comment by Moresty** [comment]
most of the issues have been fixed
